version: '3.9'
services:
    django:
        restart: always
        environment:
            DJANGO_SUPERUSER_USERNAME: admin
            DJANGO_SUPERUSER_PASSWORD: admin
            DJANGO_SUPERUSER_EMAIL: admin@gmail.com
        build: ./Backend/.
        ports:
            - 2501:2501
        command: >
            sh -c " python manage.py migrate &&
            python manage.py runserver 0.0.0.0:2501"
    react:
        build: ./Frontend/case2/.
        ports:
            - 2500:3000

    




