# Generated by Django 4.1.5 on 2023-01-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageperuser',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
